# Generated by Django 5.2.1 on 2025-05-09 20:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoColeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativa', models.BooleanField(default=True, verbose_name='Coleta Ativa')),
                ('intervalo_horas', models.PositiveIntegerField(default=24, verbose_name='Intervalo (horas)')),
                ('max_documentos', models.PositiveIntegerField(default=5, verbose_name='Máximo de Documentos')),
                ('ultima_execucao', models.DateTimeField(blank=True, null=True, verbose_name='Última Execução')),
                ('proxima_execucao', models.DateTimeField(blank=True, null=True, verbose_name='Próxima Execução')),
                ('email_notificacao', models.EmailField(blank=True, max_length=254, verbose_name='Email para Notificação')),
                ('notificar_erros', models.BooleanField(default=True, verbose_name='Notificar Erros')),
            ],
            options={
                'verbose_name': 'Configuração de Coleta',
                'verbose_name_plural': 'Configurações de Coleta',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('data_publicacao', models.DateField(verbose_name='Data de Publicação')),
                ('url_original', models.URLField(verbose_name='URL Original')),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='pdfs/', verbose_name='Arquivo PDF')),
                ('resumo', models.TextField(blank=True, verbose_name='Resumo')),
                ('texto_completo', models.TextField(blank=True, verbose_name='Texto Completo')),
                ('data_coleta', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da Coleta')),
                ('processado', models.BooleanField(default=False, verbose_name='Processado')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-data_publicacao'],
            },
        ),
        migrations.CreateModel(
            name='LogExecucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Data de Início')),
                ('data_fim', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('tipo_execucao', models.CharField(choices=[('DIARIO', 'Diário Oficial'), ('SEFAZ', 'SEFAZ'), ('COMPLETO', 'Fluxo Completo')], max_length=10, verbose_name='Tipo de Execução')),
                ('status', models.CharField(choices=[('SUCESSO', 'Sucesso'), ('ERRO', 'Erro'), ('PARCIAL', 'Sucesso Parcial')], max_length=10, verbose_name='Status')),
                ('documentos_coletados', models.IntegerField(default=0, verbose_name='Documentos Coletados')),
                ('normas_coletadas', models.IntegerField(default=0, verbose_name='Normas Coletadas')),
                ('mensagem', models.TextField(blank=True, verbose_name='Mensagem')),
                ('erro_detalhado', models.TextField(blank=True, verbose_name='Erro Detalhado')),
            ],
            options={
                'verbose_name': 'Log de Execução',
                'verbose_name_plural': 'Logs de Execução',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='NormaVigente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('LEI', 'Lei'), ('DECRETO', 'Decreto'), ('PORTARIA', 'Portaria'), ('RESOLUCAO', 'Resolução'), ('INSTRUCAO', 'Instrução Normativa'), ('OUTROS', 'Outros')], max_length=20, verbose_name='Tipo')),
                ('numero', models.CharField(max_length=50, verbose_name='Número')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data')),
                ('situacao', models.CharField(default='Vigente', max_length=50, verbose_name='Situação')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('data_coleta', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da Coleta')),
            ],
            options={
                'verbose_name': 'Norma Vigente',
                'verbose_name_plural': 'Normas Vigentes',
                'ordering': ['-data', 'tipo', 'numero'],
                'unique_together': {('tipo', 'numero')},
            },
        ),
    ]
