# Generated by Django 5.2.1 on 2025-05-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='normas_relacionadas',
            field=models.ManyToManyField(blank=True, to='monitor.normavigente'),
        ),
        migrations.AddField(
            model_name='documento',
            name='verificado_sefaz',
            field=models.BooleanField(default=False, verbose_name='Verificado na SEFAZ'),
        ),
    ]
