# Generated by Django 5.2.1 on 2025-05-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_documento_normas_relacionadas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logexecucao',
            name='data_fim',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Norma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('LEI', 'Lei'), ('PORTARIA', 'Portaria'), ('DECRETO', 'Decreto')], max_length=20)),
                ('numero', models.CharField(max_length=50)),
                ('data', models.DateField()),
                ('conteudo', models.TextField(blank=True, null=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='normas/')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('tipo', 'numero')},
            },
        ),
    ]
