# Generated by Django 5.2.1 on 2025-05-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_alter_logexecucao_data_fim_norma'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='norma',
            options={'ordering': ['-data']},
        ),
        migrations.AddField(
            model_name='norma',
            name='situacao',
            field=models.CharField(default='VIGENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='norma',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='norma',
            name='tipo',
            field=models.CharField(choices=[('LEI', 'Lei'), ('PORTARIA', 'Portaria'), ('DECRETO', 'Decreto'), ('RESOLUCAO', 'Resolução'), ('INSTRUCAO', 'Instrução Normativa')], max_length=20),
        ),
    ]
