# Generated by Django 5.2.1 on 2025-05-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_alter_norma_options_norma_situacao_norma_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='norma',
            options={},
        ),
        migrations.RemoveField(
            model_name='norma',
            name='situacao',
        ),
        migrations.RemoveField(
            model_name='norma',
            name='url',
        ),
        migrations.AddField(
            model_name='logexecucao',
            name='normas_salvas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='norma',
            name='tipo',
            field=models.CharField(choices=[('LEI', 'Lei'), ('PORTARIA', 'Portaria'), ('DECRETO', 'Decreto')], max_length=20),
        ),
    ]
