# Generated by Django 5.2.1 on 2025-05-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_alter_norma_options_remove_norma_situacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='relevante_contabil',
            field=models.BooleanField(default=False),
        ),
    ]
