# Generated by Django 5.2.1 on 2025-05-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_documento_relevante_contabil'),
    ]

    operations = [
        migrations.AddField(
            model_name='normavigente',
            name='fonte',
            field=models.CharField(choices=[('SEFAZ', 'SEFAZ'), ('DIARIO_OFICIAL', 'Diário Oficial')], default='SEFAZ', max_length=50),
        ),
    ]
