# Generated by Django 5.2.1 on 2025-05-12 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_normavigente_fonte'),
    ]

    operations = [
        migrations.AddField(
            model_name='normavigente',
            name='data_ultima_verificacao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
