# Generated by Django 5.2.1 on 2025-05-12 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0008_normavigente_data_ultima_verificacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='normavigente',
            name='data_ultima_verificacao',
        ),
    ]
