# Generated by Django 5.2.1 on 2025-05-12 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0009_remove_normavigente_data_ultima_verificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='assunto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
