# Generated by Django 5.2.1 on 2025-05-14 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0010_documento_assunto'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='processamento_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Metadados do processamento com spaCy'),
        ),
        migrations.AddField(
            model_name='normavigente',
            name='data_verificacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='normavigente',
            name='padrao_extração',
            field=models.CharField(blank=True, help_text='Padrão usado para extrair esta norma', max_length=50),
        ),
        migrations.AddField(
            model_name='normavigente',
            name='ultima_menção',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitor.documento'),
        ),
    ]
