# Generated by Django 5.2.1 on 2025-05-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0011_documento_processamento_metadata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='normavigente',
            name='data_detalhes',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da coleta de detalhes'),
        ),
        migrations.AddField(
            model_name='normavigente',
            name='detalhes_completos',
            field=models.JSONField(blank=True, default=dict, help_text='Detalhes completos coletados do portal'),
        ),
    ]
