# Generated by Django 5.2.1 on 2025-05-16 11:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0012_normavigente_data_detalhes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermoMonitorado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termo', models.CharField(max_length=255, unique=True)),
                ('tipo', models.CharField(choices=[('TEXTO', 'Texto Exato'), ('NORMA', 'Norma Específica'), ('REGEX', 'Expressão Regular')], max_length=5)),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Termo Monitorado',
                'verbose_name_plural': 'Termos Monitorados',
                'ordering': ['termo'],
            },
        ),
        migrations.DeleteModel(
            name='Norma',
        ),
        migrations.AlterModelOptions(
            name='normavigente',
            options={'ordering': ['tipo', 'numero'], 'verbose_name': 'Norma Vigente', 'verbose_name_plural': 'Normas Vigentes'},
        ),
        migrations.RemoveField(
            model_name='configuracaocoleta',
            name='notificar_erros',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='assunto',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='processamento_metadata',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='verificado_sefaz',
        ),
        migrations.RemoveField(
            model_name='logexecucao',
            name='erro_detalhado',
        ),
        migrations.RemoveField(
            model_name='logexecucao',
            name='normas_salvas',
        ),
        migrations.RemoveField(
            model_name='normavigente',
            name='data',
        ),
        migrations.RemoveField(
            model_name='normavigente',
            name='data_detalhes',
        ),
        migrations.RemoveField(
            model_name='normavigente',
            name='detalhes_completos',
        ),
        migrations.RemoveField(
            model_name='normavigente',
            name='fonte',
        ),
        migrations.RemoveField(
            model_name='normavigente',
            name='padrao_extração',
        ),
        migrations.RemoveField(
            model_name='normavigente',
            name='ultima_menção',
        ),
        migrations.AlterField(
            model_name='configuracaocoleta',
            name='ativa',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='configuracaocoleta',
            name='email_notificacao',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='configuracaocoleta',
            name='intervalo_horas',
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.AlterField(
            model_name='configuracaocoleta',
            name='max_documentos',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='configuracaocoleta',
            name='proxima_execucao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='configuracaocoleta',
            name='ultima_execucao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='normas_relacionadas',
            field=models.ManyToManyField(blank=True, related_name='documentos', to='monitor.normavigente'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='relevante_contabil',
            field=models.BooleanField(default=False, verbose_name='Relevante para Contabilidade'),
        ),
        migrations.AlterField(
            model_name='logexecucao',
            name='data_inicio',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='logexecucao',
            name='documentos_coletados',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='logexecucao',
            name='mensagem',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='logexecucao',
            name='normas_coletadas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='logexecucao',
            name='status',
            field=models.CharField(choices=[('SUCESSO', 'Sucesso'), ('ERRO', 'Erro'), ('PARCIAL', 'Sucesso Parcial')], max_length=10),
        ),
        migrations.AlterField(
            model_name='logexecucao',
            name='tipo_execucao',
            field=models.CharField(choices=[('DIARIO', 'Diário Oficial'), ('SEFAZ', 'SEFAZ'), ('COMPLETO', 'Fluxo Completo')], max_length=10),
        ),
        migrations.AlterField(
            model_name='normavigente',
            name='data_coleta',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='normavigente',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='normavigente',
            name='numero',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='normavigente',
            name='situacao',
            field=models.CharField(choices=[('VIGENTE', 'Vigente'), ('REVOGADA', 'Revogada'), ('ALTERADA', 'Alterada')], default='VIGENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='normavigente',
            name='tipo',
            field=models.CharField(choices=[('LEI', 'Lei'), ('DECRETO', 'Decreto'), ('PORTARIA', 'Portaria'), ('RESOLUCAO', 'Resolução'), ('INSTRUCAO', 'Instrução Normativa'), ('OUTROS', 'Outros')], max_length=20),
        ),
        migrations.AlterField(
            model_name='normavigente',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['data_publicacao'], name='monitor_doc_data_pu_9394a4_idx'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['processado'], name='monitor_doc_process_a9bdaf_idx'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['relevante_contabil'], name='monitor_doc_relevan_4c91df_idx'),
        ),
        migrations.AddIndex(
            model_name='logexecucao',
            index=models.Index(fields=['tipo_execucao'], name='monitor_log_tipo_ex_26e7c9_idx'),
        ),
        migrations.AddIndex(
            model_name='logexecucao',
            index=models.Index(fields=['status'], name='monitor_log_status_dc72da_idx'),
        ),
        migrations.AddIndex(
            model_name='logexecucao',
            index=models.Index(fields=['data_inicio'], name='monitor_log_data_in_a3a199_idx'),
        ),
        migrations.AddIndex(
            model_name='normavigente',
            index=models.Index(fields=['tipo', 'numero'], name='monitor_nor_tipo_bb0b64_idx'),
        ),
        migrations.AddIndex(
            model_name='normavigente',
            index=models.Index(fields=['situacao'], name='monitor_nor_situaca_d93f9f_idx'),
        ),
    ]
