# Generated by Django 5.2.1 on 2025-05-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0013_termomonitorado_delete_norma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='assunto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Assunto'),
        ),
        migrations.AddField(
            model_name='normavigente',
            name='fonte',
            field=models.CharField(choices=[('SEFAZ', 'SEFAZ'), ('DIARIO', 'Diário Oficial')], default='SEFAZ', max_length=50),
        ),
    ]
