# Generated by Django 5.2.1 on 2025-05-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0014_documento_assunto_normavigente_fonte'),
    ]

    operations = [
        migrations.AddField(
            model_name='termomonitorado',
            name='variacoes',
            field=models.TextField(blank=True, help_text='Variações do termo, separadas por vírgula', null=True),
        ),
    ]
