# Generated by Django 5.2.1 on 2025-05-19 16:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0015_termomonitorado_variacoes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioGerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CONTABIL', 'Contábil Completo'), ('MUDANCAS', 'Mudanças nas Normas'), ('ESTATISTICAS', 'Estatísticas do Sistema')], max_length=20)),
                ('caminho_arquivo', models.FileField(upload_to='relatorios/', verbose_name='Arquivo do Relatório')),
                ('formato', models.CharField(choices=[('XLSX', 'Excel (.xlsx)'), ('PDF', 'PDF (.pdf)'), ('HTML', 'HTML (.html)')], default='XLSX', max_length=10)),
                ('parametros', models.JSONField(blank=True, help_text='Parâmetros usados para gerar o relatório', null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('downloads', models.PositiveIntegerField(default=0, verbose_name='Número de Downloads')),
            ],
            options={
                'verbose_name': 'Relatório Gerado',
                'verbose_name_plural': 'Relatórios Gerados',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.AlterModelOptions(
            name='termomonitorado',
            options={'ordering': ['-prioridade', 'termo'], 'verbose_name': 'Termo Monitorado', 'verbose_name_plural': 'Termos Monitorados'},
        ),
        migrations.RenameField(
            model_name='logexecucao',
            old_name='normas_coletadas',
            new_name='documentos_processados',
        ),
        migrations.RemoveField(
            model_name='normavigente',
            name='data_coleta',
        ),
        migrations.AddField(
            model_name='configuracaocoleta',
            name='dias_retroativos',
            field=models.PositiveIntegerField(default=30, verbose_name='Dias Retroativos para Análise'),
        ),
        migrations.AddField(
            model_name='configuracaocoleta',
            name='verificar_vigencias',
            field=models.BooleanField(default=True, verbose_name='Verificar Vigências Automaticamente?'),
        ),
        migrations.AddField(
            model_name='documento',
            name='arquivo_removido',
            field=models.BooleanField(default=False, help_text='Indica se o arquivo PDF foi removido por não ser relevante'),
        ),
        migrations.AddField(
            model_name='documento',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Metadados adicionais do documento', null=True),
        ),
        migrations.AddField(
            model_name='logexecucao',
            name='duracao',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logexecucao',
            name='erro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='logexecucao',
            name='normas_verificadas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='logexecucao',
            name='traceback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='logexecucao',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='normavigente',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='normavigente',
            name='detalhes',
            field=models.JSONField(blank=True, help_text='Detalhes da consulta na SEFAZ', null=True),
        ),
        migrations.AddField(
            model_name='normavigente',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='termomonitorado',
            name='prioridade',
            field=models.PositiveSmallIntegerField(default=1, help_text='Prioridade na análise (1-5)', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='configuracaocoleta',
            name='ativa',
            field=models.BooleanField(default=True, verbose_name='Coleta Automática Ativa?'),
        ),
        migrations.AlterField(
            model_name='configuracaocoleta',
            name='email_notificacao',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail para Notificações'),
        ),
        migrations.AlterField(
            model_name='configuracaocoleta',
            name='intervalo_horas',
            field=models.PositiveIntegerField(default=24, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Intervalo entre Coletas (horas)'),
        ),
        migrations.AlterField(
            model_name='configuracaocoleta',
            name='max_documentos',
            field=models.PositiveIntegerField(default=10, verbose_name='Máximo de Documentos por Coleta'),
        ),
        migrations.AlterField(
            model_name='configuracaocoleta',
            name='proxima_execucao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Próxima Execução'),
        ),
        migrations.AlterField(
            model_name='configuracaocoleta',
            name='ultima_execucao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última Execução'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='arquivo_pdf',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='pdfs/', verbose_name='Arquivo PDF'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='assunto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='data_coleta',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='documento',
            name='normas_relacionadas',
            field=models.ManyToManyField(blank=True, related_name='documentos', to='monitor.normavigente', verbose_name='Normas Relacionadas'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='processado',
            field=models.BooleanField(default=False, verbose_name='Processado?'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='relevante_contabil',
            field=models.BooleanField(default=False, verbose_name='Relevante para Contabilidade?'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='url_original',
            field=models.URLField(max_length=500, verbose_name='URL Original'),
        ),
        migrations.AlterField(
            model_name='logexecucao',
            name='status',
            field=models.CharField(choices=[('SUCESSO', 'Sucesso'), ('ERRO', 'Erro'), ('PARCIAL', 'Sucesso Parcial')], max_length=20),
        ),
        migrations.AlterField(
            model_name='logexecucao',
            name='tipo_execucao',
            field=models.CharField(choices=[('DIARIO', 'Coleta do Diário Oficial'), ('SEFAZ', 'Verificação na SEFAZ'), ('PROCESSAMENTO', 'Processamento de Documentos'), ('RELATORIO', 'Geração de Relatório'), ('COMPLETO', 'Fluxo Completo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='normavigente',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição/Objeto'),
        ),
        migrations.AlterField(
            model_name='normavigente',
            name='situacao',
            field=models.CharField(choices=[('VIGENTE', 'Vigente'), ('REVOGADA', 'Revogada'), ('ALTERADA', 'Alterada'), ('A_VERIFICAR', 'A Verificar')], default='A_VERIFICAR', max_length=20),
        ),
        migrations.AlterField(
            model_name='normavigente',
            name='url',
            field=models.URLField(blank=True, verbose_name='URL da Norma'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['arquivo_removido'], name='monitor_doc_arquivo_364161_idx'),
        ),
        migrations.AddIndex(
            model_name='normavigente',
            index=models.Index(fields=['data_verificacao'], name='monitor_nor_data_ve_d2b0af_idx'),
        ),
        migrations.AddIndex(
            model_name='termomonitorado',
            index=models.Index(fields=['ativo'], name='monitor_ter_ativo_aa9a91_idx'),
        ),
        migrations.AddIndex(
            model_name='termomonitorado',
            index=models.Index(fields=['tipo'], name='monitor_ter_tipo_9059ea_idx'),
        ),
        migrations.AddField(
            model_name='relatoriogerado',
            name='gerado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='relatoriogerado',
            index=models.Index(fields=['tipo'], name='monitor_rel_tipo_72e75e_idx'),
        ),
        migrations.AddIndex(
            model_name='relatoriogerado',
            index=models.Index(fields=['data_criacao'], name='monitor_rel_data_cr_2235bd_idx'),
        ),
    ]
