# Generated by Django 5.2.1 on 2025-05-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0016_relatoriogerado_alter_termomonitorado_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logexecucao',
            name='detalhes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
