# Generated by Django 5.2.1 on 2025-05-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0017_logexecucao_detalhes'),
    ]

    operations = [
        migrations.AddField(
            model_name='normavigente',
            name='data_ultima_mencao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
