# Generated by Django 5.2.1 on 2025-05-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0018_normavigente_data_ultima_mencao'),
    ]

    operations = [
        migrations.AddField(
            model_name='normavigente',
            name='irregular',
            field=models.BooleanField(default=False, verbose_name='Norma Irregular'),
        ),
        migrations.AlterField(
            model_name='normavigente',
            name='situacao',
            field=models.CharField(choices=[('VIGENTE', 'Vigente'), ('REVOGADA', 'Revogada'), ('IRREGULAR', 'Irregular'), ('A_VERIFICAR', 'A verificar')], default='A_VERIFICAR', max_length=20),
        ),
    ]
