# Generated by Django 5.2.1 on 2025-05-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0019_normavigente_irregular_alter_normavigente_situacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='normavigente',
            options={'ordering': ['tipo', '-ano', 'numero'], 'verbose_name': 'Norma Vigente', 'verbose_name_plural': 'Normas Vigentes'},
        ),
        migrations.RemoveIndex(
            model_name='normavigente',
            name='monitor_nor_tipo_bb0b64_idx',
        ),
        migrations.AlterUniqueTogether(
            name='normavigente',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='normavigente',
            name='ano',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='normavigente',
            name='numero',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='normavigente',
            name='situacao',
            field=models.CharField(choices=[('VIGENTE', 'Vigente'), ('REVOGADA', 'Revogada'), ('IRREGULAR', 'Irregular'), ('A_VERIFICAR', 'A verificar'), ('ALTERADA', 'Alterada'), ('DESCONHECIDA', 'Desconhecida')], default='A_VERIFICAR', max_length=20),
        ),
        migrations.AlterField(
            model_name='normavigente',
            name='tipo',
            field=models.CharField(choices=[('LEI', 'Lei'), ('DECRETO', 'Decreto'), ('PORTARIA', 'Portaria'), ('RESOLUCAO', 'Resolução'), ('INSTRUCAO', 'Instrução Normativa'), ('OUTROS', 'Outros')], db_index=True, max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='normavigente',
            unique_together={('tipo', 'numero', 'ano')},
        ),
        migrations.AddIndex(
            model_name='normavigente',
            index=models.Index(fields=['tipo', 'numero', 'ano'], name='monitor_nor_tipo_a20a52_idx'),
        ),
    ]
