# Generated by Django 5.2.1 on 2025-05-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0020_alter_normavigente_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='url_original',
            field=models.URLField(db_index=True, max_length=500, unique=True, verbose_name='URL Original'),
        ),
    ]
