# Generated by Django 5.2.1 on 2025-05-23 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0021_alter_documento_url_original'),
    ]

    operations = [
        migrations.AddField(
            model_name='normavigente',
            name='fonte_confirmacao',
            field=models.CharField(blank=True, choices=[('SEFAZ', 'SEFAZ'), ('BING', 'Bing')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='normavigente',
            name='resumo_ia',
            field=models.TextField(blank=True, null=True, verbose_name='Resumo da IA'),
        ),
        migrations.AddField(
            model_name='normavigente',
            name='url_consulta',
            field=models.URLField(blank=True, null=True, verbose_name='URL de consulta'),
        ),
        migrations.AlterField(
            model_name='normavigente',
            name='data_verificacao',
            field=models.DateTimeField(auto_now=True, default=datetime.date(2025, 5, 23), verbose_name='Data da última verificação'),
            preserve_default=False,
        ),
    ]
