# Generated by Django 5.2.1 on 2025-05-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0022_normavigente_fonte_confirmacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normavigente',
            name='data_verificacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da última verificação'),
        ),
    ]
