# Generated by Django 5.2.1 on 2025-05-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0024_documento_fonte_documento_documento_tipo_documento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='resumo_ia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='sentimento_ia',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
