# Generated by Django 5.2.1 on 2025-05-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0025_documento_resumo_ia_documento_sentimento_ia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='sentimento_ia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
