# Generated by Django 5.2.1 on 2025-07-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0027_alter_documento_sentimento_ia'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='impacto_fiscal',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Impacto Fiscal'),
        ),
    ]
