# Generated by Django 5.2.1 on 2025-07-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0028_documento_impacto_fiscal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='assunto',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='impacto_fiscal',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Impacto Fiscal'),
        ),
    ]
