# Generated by Django 5.2.1 on 2025-08-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0029_alter_documento_assunto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AliquotaUf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(max_length=2)),
                ('data', models.DateField()),
                ('dados', models.JSONField()),
            ],
            options={
                'db_table': 'aliquota_uf',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AliquotaUniao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('dados', models.JSONField()),
            ],
            options={
                'db_table': 'aliquota_uniao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClassificacoesTributariasCbsIbs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('dados', models.JSONField()),
            ],
            options={
                'db_table': 'classificacoes_tributarias_cbs_ibs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClassificacoesTributariasImpostoSeletivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('dados', models.JSONField()),
            ],
            options={
                'db_table': 'classificacoes_tributarias_imposto_seletivo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FundamentacoesLegais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('dados', models.JSONField()),
            ],
            options={
                'db_table': 'fundamentacoes_legais',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SituacoesTributariasCbsIbs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('dados', models.JSONField()),
            ],
            options={
                'db_table': 'situacoes_tributarias_cbs_ibs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SituacoesTributariasImpostoSeletivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('dados', models.JSONField()),
            ],
            options={
                'db_table': 'situacoes_tributarias_imposto_seletivo',
                'managed': False,
            },
        ),
    ]
