# Generated by Django 5.2.1 on 2025-08-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0030_aliquotauf_aliquotauniao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='is_contabeis_news',
            field=models.BooleanField(default=False, help_text='Indica se o documento foi coletado do site Contabeis.', verbose_name='Notícia do Contabeis?'),
        ),
    ]
