# Generated by Django 5.2.1 on 2025-08-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0031_documento_is_contabeis_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='docs_sefaz',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='pdfs_sefaz/', verbose_name='PDF SEFAZ'),
        ),
    ]
